AllCops:
  Exclude:
    - config/unicorn.rb
    #- db/**
    - db/schema.rb
    - vendor/**/*
    - bin/**
    - lib/tasks/sample.rake
    - lib/jellyfish_fog_aws/spec/dummy/**/*
  RunRailsCops: true

ClassLength:
  Max: 300

MethodLength:
  Max: 50

Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 38

Style/GlobalVars:
  AllowedVariables: [$evm]
